Remove unusable environment variable. updated to latest version of dedicated server in DST. For more setting guide refer to https://forums.kleientertainment.com/topic/64552-dedicated-server-settings-guide/

diff --git a/rootfs/etc/entrypoint.d/2-checks b/rootfs/etc/entrypoint.d/2-checks
--- a/rootfs/etc/entrypoint.d/2-checks
+++ b/rootfs/etc/entrypoint.d/2-checks
@@ -1,13 +1,7 @@
 #!/bin/bash
 
-if [ -z "${DST_SERVER_TOKEN}" ]
+if [ -z "${DST_CLUSTER_TOKEN}" ]
 then
-  echo >&2 "Error: Please provide a DST_SERVER_TOKEN value"
-  exit 1
-fi
-
-if [ -z "${DST_CLUSTER_KEY}" ]
-then
-  echo >&2 "Error: Please provide a DST_CLUSTER_KEY value"
+  echo >&2 "Error: Please provide a DST_CLUSTER_TOKEN value"
   exit 1
 fi
